<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<PackageId>CommonIR</PackageId>
	<Version>1.1.3</Version>
	<Authors>Draugr-official</Authors>
	<Company>Compiler Organization</Company>
	<Description>Generic IR to support a variety of different targets, such as WASM, x8664, and other modern architectures.</Description>
	<RepositoryUrl>https://github.com/Compiler-Organization/CommonIR</RepositoryUrl>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	<PackageReleaseNotes>Fixed some issues with how IRCalls were handled internally. Can now be cast to IRValueInstruction if returning a value.</PackageReleaseNotes>
	<PackageProjectUrl>https://github.com/Compiler-Organization/CommonIR</PackageProjectUrl>
	<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CommonIR.App\**" />
    <EmbeddedResource Remove="CommonIR.App\**" />
    <None Remove="CommonIR.App\**" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Documentation\" />
  </ItemGroup>

</Project>
